# Generated by Django 5.1.7 on 2025-03-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('info', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('hot', models.CharField(max_length=255)),
                ('uptime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Bd',
            },
        ),
        migrations.CreateModel(
            name='Bl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('info', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('hot', models.CharField(max_length=255)),
                ('uptime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Bl',
            },
        ),
        migrations.CreateModel(
            name='CrawlTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wbtime', models.IntegerField()),
                ('Bdtime', models.IntegerField()),
                ('Bltime', models.IntegerField()),
            ],
            options={
                'db_table': 'CrawlTime',
            },
        ),
        migrations.CreateModel(
            name='Wb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('info', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('hot', models.CharField(max_length=255)),
                ('uptime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Wb',
            },
        ),
    ]
