# Generated by Django 5.1.7 on 2025-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='uptime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bl',
            name='uptime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wb',
            name='uptime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
