# Generated by Django 5.1.7 on 2025-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bd_uptime_alter_bl_uptime_alter_wb_uptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wbtime', models.IntegerField()),
                ('Bdtime', models.IntegerField()),
                ('Bltime', models.IntegerField()),
            ],
            options={
                'db_table': 'PushTime',
            },
        ),
    ]
